### ISSUE TITLE
Sharing is unreliable

### ISSUE THREAD

**Issue by evanmiller** [jerrykrinock/BSManagedDocument#15]
10.13 and later enable a "Share" menu on the document. I've found this function to be unreliable with BSManagedDocument in at least two ways:

* If the document is unsaved (auto-saved), a "Failed other writing" error occurs
* If the document is saved, the first Share seems to work fine, but the second Share results in a hang

A workaround is to return `NO` from [`allowsDocumentSharing`](https://developer.apple.com/documentation/appkit/nsdocument/2902303-allowsdocumentsharing?language=objc), which disables the Share menu entirely. (In my test app, it doesn't actually remove Share from the File menu, but rather removes the individual Share actions.)

**Comment by evanmiller** [comment]
A better workaround is to subclass `NSDocumentController`, override [`allowsAutomaticShareMenu`](https://developer.apple.com/documentation/appkit/nsdocumentcontroller/2902308-allowsautomaticsharemenu?language=objc) to return `NO`, and then install the subclass by initializing an instance during `applicationWillFinishLaunching:`.

This procedure erases Share from the File menu entirely.

**Comment by jerrykrinock** [comment]
Very good, Evan.  I's never noticed that File > Share submenu and apparently none of my users have ever tried it.  My apps do not have data which users would want to "share", so I used your "better workaround" and all is good.

Knowing the modern-day complexity of NSDocument, I suspect that fixing this would be very time consuming.  And I would not be surprised if Sharing turned out to be unreliable with NSPersistentDocument also :))  Anyhow, as far as I am concerned, until someone needs Sharing and wants to dig in, we are going to leave this issue unsolved, with your nice workaround.

**Comment by evanmiller** [comment]
According to this:

https://developer.apple.com/documentation/appkit/nsdocument/2902309-sharedocumentwithsharingservice?language=objc

The system forces an autosave before copying it out. I'm guessing that to support Sharing, BSManagedDocument will need to implement its voodoo in the function `shareDocumentWithSharingService:completionHandler:`. I'm not sure if that will involve zipping the package or if the OS hides those details.

I'll let you know if I get around to investigating, but it's not a high priority. It might be worth implementing the first (inferior) workaround in BSManagedDocument to prevent others from getting snagged.

**Comment by evanmiller** [comment]
Some notes for myself:

If the document lacks a `fileURL`, NSDocument performs an `NSAutosaveElsewhereOperation` at a temporary location outside the usual Autosave directory. BSManagedDocument doesn't know what to do in this situation and defers to super's `writeSafelyToURL:`. The package directory structure is not created by the `writingBlock` because `fileURL` is nil.

There needs to be logic in some place to create the package and associate the coordinator with the temporary URL without using the usual `autosavedContentsFileURL` mechanism. Or possibly we can just blast out a backup to the temporary location and forget about keeping tabs on the persistent stores. This might be easier with #17 in place since documents are basically always backed by stores in that PR.

An `isSharing` flag might be set by overriding `shareDocumentWithSharingService:completionHandler:` so that the internal functions are aware that a share is happening.
