### ISSUE TITLE
File > Duplicate on Edited document makes new document without the edits

### ISSUE THREAD

**Issue by jerrykrinock** [jerrykrinock/BSManagedDocument#6]
File > Duplicate on an unsaved ("Edited") document produces a new document which does not have any of the unsaved changes from the original document.

This goes back at least several months in my apps, so it is apparently not caused by anything I recently pulled from Evan or Mike.  Maybe we should test this in the BSManagedDocument test app. It's easy to imagine how this could occur, given the fundamental that Core Data only reads into memory from its SQLite store as needed.

Just tested this in last version of Sandvox and it works correctly.

**Comment by jerrykrinock** [comment]
Short version:  Running my latest commit in BSTestApp, _File_ > _Duplicate_ works correctly.  So I think this is a non-issue.

Longer:   I think the misbehavior, which I saw in one of *my* client apps, is due to a workaround for bug(s) in `NSPersistentDocument`, in my client application code many years ago.  Will confirm and comment again here later.

**Comment by evanmiller** [comment]
FWIW I am not able to reproduce this bug while running the latest code.

**Comment by jerrykrinock** [comment]
Yes, as I mentioned in my last comment, the problem is probably in my app's code because the BSTest app does not have this bug.  I'm still looking for the problem in my code.

**Comment by jerrykrinock** [comment]
This is no longer an issue.  It must have been in my app's code.
